---
- name: Playbook for VPC
  hosts: localhost
  tasks:
    - name: VPC for class
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tags:
          Class: Ansible
          Task: VPC
    - name: Collect VPC info
      ec2_vpc_net_facts:
        region: "{{region}}"
        filters:
          "tag:Task": VPC
      register: VPC1

    - name: Create Public Subnet 1
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        cidr: "{{Public_cidr1}}"
        resource_tags:
          Name: dev
      register: vpc-task-public

    - name: Create Public Subnet 2
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        cidr: "{{Public_cidr2}}"
        resource_tags:
          Name: dev
      register: vpc-task-subnet-2

    - name: Create Public Subnet 3
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        cidr: "{{Public_cidr3}}"
        resource_tags:
          Name: dev
      register: vpc-task-subnet-3


    - name: Create Private Subnet 1
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        cidr: "{{Private_cidr1}}"
        resource_tags:
          Name:  dev
      register: subnet-task

    - name: Create Private Subnet 2
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        cidr: "{{Private_cidr2}}"
        resource_tags:
          Name: dev
      register: subnet-task2

    - name: Create Private Subnet 3
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        cidr: "{{Private_cidr3}}"
        resource_tags:
          Name: dev
      register: subnet-task3 
      